spring:
  application:
    name: task-manager
camunda:
  bpm:
    admin-user:
      id: camunda
      password: camunda
      firstName: camunda
    filter:
      create: All tasks
    authorization:
      enabled: true
    database:
      type: h2
  deployment-resource-pattern:
    - bp/*
